# Generated by Django 2.0.3 on 2018-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180313_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='public_key',
            field=models.CharField(db_index=True, default='', max_length=66),
            preserve_default=False,
        ),
    ]
