# Generated by Django 2.0.3 on 2018-03-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delegate_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='missed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
