# Generated by Django 2.0.3 on 2018-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_history_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='has_arkstats',
            field=models.BooleanField(default=False),
        ),
    ]
