# Generated by Django 2.0.3 on 2018-03-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180327_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
