# Generated by Django 2.0.3 on 2018-03-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180327_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='cpu',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='disk',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='memory',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='os',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='provider',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='timezone',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
