# Generated by Django 2.0.3 on 2018-03-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180327_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='network',
            field=models.CharField(choices=[('mainnet', 'mainnet'), ('devnet', 'devnet')], default='mainnet', max_length=10),
        ),
    ]
