# Generated by Django 2.0.3 on 2018-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180330_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='voting_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
