# Generated by Django 2.0.3 on 2018-04-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_history_voting_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='voting_power',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
