# Generated by Django 2.0.3 on 2018-04-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180401_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
