# Generated by Django 2.0.3 on 2018-04-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180405_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='disk',
        ),
        migrations.RemoveField(
            model_name='node',
            name='location',
        ),
        migrations.RemoveField(
            model_name='node',
            name='os',
        ),
        migrations.RemoveField(
            model_name='node',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='node',
            name='timezone',
        ),
        migrations.AddField(
            model_name='node',
            name='is_dedicated',
            field=models.BooleanField(default=False),
        ),
    ]
