# Generated by Django 2.0.4 on 2018-04-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_claimaccointpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
