# Generated by Django 2.0.4 on 2018-04-25 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_statusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
