# Generated by Django 2.0.4 on 2018-04-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180425_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusupdate',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
