# Generated by Django 2.0.5 on 2018-05-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180426_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegate',
            name='payout_covering_fee',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payout_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payout_maximum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payout_maximum_vote_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payout_minimum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payout_minimum_vote_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='delegate',
            name='payout_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
