# Generated by Django 2.0.5 on 2018-05-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180507_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='rank_changed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
