# Generated by Django 2.1.7 on 2019-03-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_contribution_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delegate',
            name='is_private',
            field=models.NullBooleanField(),
        ),
    ]
