# Generated by Django 2.2.2 on 2019-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20190708_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegate',
            options={'permissions': [('payout_change', 'Can change payouts info of all delegates')]},
        ),
        migrations.AlterField(
            model_name='historicalcontribution',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicaldelegate',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalstatusupdate',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
