version: '3'

services:
  web:
    build:
      context: .
    command: uwsgi --http-socket 0.0.0.0:5000 --honour-stdin --ini etc/uwsgi.ini --python-autoreload 1 --processes 1
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - redis
    environment:
      DEBUG: '1'
      PORT: '5000'
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/postgres'
      NEW_RELIC_DEVELOPER_MODE: 1
      NEW_RELIC_LICENSE_KEY: '123456789'
      CORS_ORIGIN_WHITELIST: 'http://localhost:3000'
    volumes:
      - .:/app
    expose:
      - "5000"
    ports:
      - "5000:5000"

  db:
    image: postgres:9.6
    networks:
      - backend
    ports:
      - "5432"
    volumes:
      - db-data:/data/db

  redis:
    image: redis:alpine
    networks:
      - backend

volumes:
  db-data:

networks:
  frontend:
  backend:
