[tool.black]
line-length = 100
target-version = ['py37', 'py38']
skip-numeric-underscore-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | static
  | dist
  | migrations
  | node_modules
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''
